language: python
python:
- '3.7'
- '3.8'
addons:
  apt:
    update: true
    sources:
    - google-chrome
    packages:
    - dpkg
    - google-chrome-stable
install:
- pip install -r requirements.txt
script:
- python -m unittest tests/test_oauth_initializer.py
- python -m unittest tests/test_zaim_api.py
- python -m unittest tests/test_crawler.py
notifications:
  slack:
    secure: QyvDrZIKQhJ3Mr9P6mODncyRajcmFmk/a7bhgmLhcItjyn8enUoRfDoqSg/Iebn+4v+02TV2WE0ss3qBhqwbVy9U3c0hFv6j56yMidnxz+WXyDk+KMpcOppG2EgO85wmMfp748MRAFjL2WP1HfFmSoR4op50UPSA2gCFbygcDcFiod5Pzd6sTw4e0gDCdVwK6uEbb31dDou1fyH1JXh6iX/q3oNZzFJoCQuTZTgtZmP/Nt/QhfgMLyUaD5DourFdOzB9Y0IK7T11GMwolmT7biMP5i6tAs58JCqiHxOrw+PHs0FEglPOj2a4pckegLj0ouR0dlNhqh7zjCT/6oLsUpnsDGbXQfZj9osDD2dWv4W2I0bGon/WwiUXjPTKc+1YCqx6PjvtcPc5t/NmnzBq7NFtJDvEijkR6dBDGKhR7kOnloR/JktXrlsXbpOxPSLkKqPiY1hrAfMo6GRKTDnnIQDR9GQs5L5U4K2lYcnlqcNQSC8sHm2DKQyfBrQ/dcUDxIHLwrXz3HrSoXJfqQJZmo+dgWJeiG7e1MWMymhpWyppuSfrhgIagfh/Z6uYh31sjc7WzoSJaOO2z4gdXzvbQ3XjwF75cN02ROiagvAlXHN0HLFlpdAEQ+f/hyq8N4XMb/T5w4k2+Km6fHkHZaQ2/9UEBLf5rn+RSpQ9Nrr4gZQ=
  webhooks:
    secure: "cy3n4VreUWmg8U4LE4M4wzqYGDP0OoY9+Bmqe3PI0wIpaulxw5609XH3Df0rKmlBB5P5sa4uV+O6uEb2/OEyDsmZgcf1tSRDa20nGYXmXy4u43HraJrZQrieWQpDWC9aDZz1lKDERl+zhH24S9jOSNlfCU/lq8TCsU8RDj9Lbg0nGR9T71Ket5D80SVyhKVbpZRczO41M64C1Fcp4FAxcVxgAz5iddRyi3TMt0vF7p2cO1LbISKFc7S+o3thRkj4UaawikufQOaFL3TntFyIGkYVkLYg+T1GCAYibG6FuupX7xxSZcsdohzWVxljSpTzojVLwi73dFshRTiEP3KkHpS3cpARgA50I7VrJgWUaMKN+cJwhZVceYVq1r+/zfLpYvRZjtU9xnjE3m7gD5VaHd2lCnQTWPU+MjdkaOLuANYTC14AzT+z178wHDIg8XH/sgw1/U78qIMyMmeNve7OjRwOqn1fP4ue1dANzgx1aOx0sXMrXCzrpzLAZ1JmICiqeq0ojhyt2wqbBeTIvOLbFPQrW2CVAhyFY5Akj78BON2jQVAIx24tt8tqOha+AOk3U3ZDyYsmOjuLJthUscypZzRYY0luLCbbQ4epWtPdPlOTfZNiRh3ZGjUxhI6ZHVj4SAp7rmBhuzWDvkAGLGjEfYOWS1YkMAtcou6cB/gSZVo="

