language: python
python:
  - "3.7"
  - "3.8"
addons:
  apt:
    update: true
    sources:
     - google-chrome
    packages:
     - dpkg
     - google-chrome-stable
install:
  - pip install -r requirements.txt
script:
  - python -m unittest tests/test_oauth_initializer.py
  - python -m unittest tests/test_zaim_api.py
  - python -m unittest tests/test_crawler.py