language: python
python:
- '3.7'
- '3.8'
addons:
  apt:
    update: true
    sources:
    - google-chrome
    packages:
    - dpkg
    - google-chrome-stable
install:
- pip install -r requirements.txt
script:
- python -m unittest tests/test_oauth_initializer.py
- python -m unittest tests/test_zaim_api.py
- python -m unittest tests/test_crawler.py
notifications:
  slack:
    secure: QyvDrZIKQhJ3Mr9P6mODncyRajcmFmk/a7bhgmLhcItjyn8enUoRfDoqSg/Iebn+4v+02TV2WE0ss3qBhqwbVy9U3c0hFv6j56yMidnxz+WXyDk+KMpcOppG2EgO85wmMfp748MRAFjL2WP1HfFmSoR4op50UPSA2gCFbygcDcFiod5Pzd6sTw4e0gDCdVwK6uEbb31dDou1fyH1JXh6iX/q3oNZzFJoCQuTZTgtZmP/Nt/QhfgMLyUaD5DourFdOzB9Y0IK7T11GMwolmT7biMP5i6tAs58JCqiHxOrw+PHs0FEglPOj2a4pckegLj0ouR0dlNhqh7zjCT/6oLsUpnsDGbXQfZj9osDD2dWv4W2I0bGon/WwiUXjPTKc+1YCqx6PjvtcPc5t/NmnzBq7NFtJDvEijkR6dBDGKhR7kOnloR/JktXrlsXbpOxPSLkKqPiY1hrAfMo6GRKTDnnIQDR9GQs5L5U4K2lYcnlqcNQSC8sHm2DKQyfBrQ/dcUDxIHLwrXz3HrSoXJfqQJZmo+dgWJeiG7e1MWMymhpWyppuSfrhgIagfh/Z6uYh31sjc7WzoSJaOO2z4gdXzvbQ3XjwF75cN02ROiagvAlXHN0HLFlpdAEQ+f/hyq8N4XMb/T5w4k2+Km6fHkHZaQ2/9UEBLf5rn+RSpQ9Nrr4gZQ=
  webhooks:
    secure: "gaXebWIPM8USfoq8EgRd8GRAPvHhYIBfeL4PqqGdIQXPpwEyLbhzu8aT9+6XlAMlZAusKpYKvQ0ElLG3kTNM2641vkNjpn/R9F4/TDNoUIupEDzGbsdBZvASGi9/cYzwJZh1VPRlQBE3XUfzsW0eU7cjsqyd+6hkq1kwkYzx+2yTNkF/cjblA4mVFWrmMzs43313hKOYB6jX8bCuIvnwtrntnRD3htAhTfPs9P9NXsBafzmF76Q7/xkmua3kCgCMIx22cEoFZDqFRoW47ODBC1Mag5IycqL6+tdAgMGPwHr/W8xDzF6Z3L0rgtRquc5s+jjaQcOl+shHJgV4QABJY1UbXpifPCLRTuwv3wJ49jDW/GzUtq7EzKet1MIf52R7RhvUltK8SIy5kl6aBlnCU+lLW6Xl2VyGzGW1fuPnTMDa5WJD+nRjSQUMfg8FHkl9QymcIIYunth6ccGrhkDQ+bQObs9ZQT68Qdqjg9niImWrB/zPpzry1fB2TBgfbOeqMYT8VUKjm3VuxrLHX02lHVh1Db1Qj9I0UnNdvbs0gxV8raiBMcCjkTO8RHc0oS9OcgR9VAL2y3o9i9NWyRHtppUzrU4qLgGy2H04E5JuWmcbMXOgND6GPZgJvfXaTSRyHerUNZs0JfenxbAlkXgoSncDiQmjoapMXXH2ty7Dz4c="

